# When it happens
on: # Run the action:
  push: # On a push
    branches:
      - main # To the main branch
  workflow_dispatch: # When we click
# What it does
jobs: # What to do
  quality_check:
    name: "Quality Check"
    runs-on: ubuntu-latest
    steps:
      # Get access to the repo code
      - name: "Get repo"
        uses: actions/checkout@v6 # Use a built-in, existing action
      # Install Python
      - name: "Install Python"
        uses: actions/setup-python@v6 
      # Install all relevant libraries
      - name: "Install libraries"
        run: pip install -r requirements.txt
      # Run Pytest/pylint
      - name: "Run tests"
        run: pytest
