# When it happens
on: # Run the action:
  push: # On a push
    branches:
      - main # To the main branch
  workflow_dispatch: # When we click
# What it does
jobs: # What to do
  example:
    name: "Example job"
    runs-on: ubuntu-latest
    steps: # What specifically to do (basically shell comamnds)
      - name: "Step 1"
        run: echo "hi!" # Run a basic shell command
      - name: "Step 2"
        run: echo "Hi again!"
